image: maven:3.6.1-jdk-11

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

# Cache the Maven repository so that each job does not have to download it.
cache:
  key: mavenrepo
  paths:
    - .m2/repository

stages:
  - build
  - test
  - generate-doc

build:
  stage: build
  tags:
    - shell
  script:
    - mvn $MAVEN_OPTS compile

test:
  stage: test
  tags:
    - shell
  script:
    - mvn $MAVEN_OPTS test
  allow_failure: true
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

generate-doc:
  stage: generate-doc
  allow_failure: true
  tags:
    - shell
  script:
    - mvn javadoc:javadoc
  artifacts:
    when: always