image: maven:3.6.1-jdk-11

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

# Cache the Maven repository so that each job does not have to download it.
cache:
  key: mavenrepo
  paths:
    - ./.m2/repository/

stages:
  - build
  - test

build:
  stage: build
  tags:
    - shell
  script:
    - mvn $MAVEN_OPTS compile

test:
  stage: test
  tags:
    - shell
  script:
    - mvn $MAVEN_OPTS test